<?php
/**
 * Evince_Ourteam extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Evince
 * @package		Evince_Ourteam
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Our Team list template
 *
 * @category	Evince
 * @package		Evince_Ourteam
 * @author Evince Development
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$_ourteams = $this->getOurteams();
?>
<div class="page-title ourteam-title">
    <h1><?php echo Mage::helper('ourteam')->__('Our Team') ?></h1>
</div>
<?php if ($_ourteams->getSize() > 0) : ?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="ourteam-list-container">
        <ul class="teamGallery">
            <?php foreach ($_ourteams as $_ourteam) : ?>
                <li class="ourteam-list-item">
                     <a href="<?php echo $_ourteam->getOurteamUrl(); ?>" title="<?php echo $this->htmlEscape($_ourteam->getName()) ?>">
                     <?php if($_ourteam->getImage()){ ?>
                    <img class="member_avatar " src="<?php echo $media_url . "ourteam/image" . $_ourteam->getImage() ?>" alt="<?php echo $_ourteam->getName(); ?>" width="190" height="190"/>
                    <?php } else { ?>
                        <img class="member_avatar" src="<?php echo $this->getSkinUrl('images/placeholder/ourteam.jpg')?>" alt="<?php echo $_ourteam->getName(); ?>" width="190" height="190"/>
                   <?php  }?>
                    <h2 class="member_name">
                            <?php echo $_ourteam->getName(); ?>
                        
                    </h2></a>
                        
                    <?php
                    if ($_ourteam->getDesignation()) {
                        ?>
                        <div id="greg_description"><?php echo $_ourteam->getDesignation(); ?>	
                        <?php } ?>
                        
                    </div>
                       <?php if ($_ourteam->getDescription()) {
                            ?>
                           
                    <a class="read-more" href="<?php echo $_ourteam->getOurteamUrl(); ?>" title="<?php echo $this->htmlEscape($_ourteam->getName()) ?>">
                                <?php echo __('View'); ?>	
                            </a>
                        <?php } ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('ourteam')->__('There are no our team at this moment'); ?>
<?php endif; ?>