<?php $enable = Mage::getStoreConfig('buyxgetyfree_section2/general/enable'); ?>
<?php if ($enable == '1'): ?>

    <?php
    /* @var $this PAJ_BuyXGetYFree_Block_Freeproduct */

    $showPopup = $this->isShowPopup();
    $_productCollection = $this->getFreeProducts();

    $config_products = array();
    $_helper = $this->helper('catalog/output');
    $theme = $this->helper('ultimo');
    $helpLabels = $this->helper('ultimo/labels');
    $helpImg = $this->helper('infortis/image');
    $columnCount = 2;
    //Image size
    $imgWidth = intval($theme->getCfg('category/image_width'));
    $imgHeight = $imgWidth;

    //If image width is not specified, use default values
    if ($imgWidth <= 0) {
        $imgWidth = 250;
        $imgHeight = 250;
    }
    $spendProductYDescription = Mage::getStoreConfig('buyxgetyfree_section2/general/spend_producty_description');

    ?>

    <?php if ($showPopup && ($_productCollection->count() > 0)): ?>


        <a id="trigger_free_products" href="#free_products_container" title="" style="display: none"></a>
        <div style="display: none">
            <div id="free_products_container" style="width:500px;height:400px;overflow:auto;" class="category-products">
                <h3 style="margin-top: 10px"><?php echo $spendProductYDescription; ?></h3>
                <ul class="products-grid category-products-grid itemgrid itemgrid-adaptive itemgrid-<?php echo $columnCount; ?>col single-line-name centered size-s">
                    <?php
                    foreach ($_productCollection as $_product):
                        $stylecode = $_product->getStylecode();
                        if (!isset($config_products[$stylecode])) {
                            $config_products[$stylecode] = Mage::getModel('catalog/product')->load(Mage::getModel('catalog/product')->getResource()->getIdBySku($stylecode));
                        }
                        $urlProduct = $config_products[$stylecode]->getProductUrl() . '?pi=' . $_product->getId();
                        ?>
                        <li class="item" style="height: auto !important;">

                            <div class="product-image-wrapper"
                                 style="max-width:<?php echo $imgWidth; ?>px;height: auto">

                                <a href="#" title="<?php echo $_product->getName(); ?>"
                                   class="product-image">
                                    <img width="150px" height="150px"
                                         id="free-product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php echo $helpImg->getImage($_product->getId(), 'small_image'); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true); ?>"/>

                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                                    <?php endif; ?>

                                    <?php echo $helpLabels->getLabels($_product); //Product labels
                                    ?>
                                </a>

                            </div>
                            <!-- end: product-image-wrapper -->

                            <h2 class="product-name<?php echo $productNameClasses; ?>">
                                <a href="#"
                                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h2>

                            <div class="actions clearer">

                                <?php if ($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                            class="button btn-cart"
                                            onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                        <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                    </button>
                                <?php else: ?>
                                    <p class="availability out-of-stock">
                                        <span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>

                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <script type="text/javascript" language="javascript">
            jQuery(document).ready(function () {
                jQuery("#trigger_free_products").fancybox().trigger('click');
            });
        </script>

    <?php endif; ?>
<?php endif; ?>
