<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
$productId = Mage::app()->getRequest()->getParam('pi', 0);
$simpleProduct = null;
if ($productId):
    $simpleProduct = Mage::getModel('catalog/product')
            ->load($productId);
endif;
if ($simpleProduct) {
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $theme = $this->helper('ultimo');
    $helperThis = $this->helper('ultimo/template_catalog_product_view');
    $helperSnippets = $this->helper('ultimo/rsnippets');
   
//CSS classes based on product type
    $productTypeId = $_product->getTypeId();
    $productTypeClasses = '';
    if ($productTypeId === 'grouped') {
        $productTypeClasses .= ' is-type-grouped';
    }

//
    $shortDescription = $_helper->productAttribute($simpleProduct, nl2br($simpleProduct->getShortDescription()), 'short_description');

//Rich snippets
    $useRichSnippets = ($helperSnippets->isEnabledOnProductPage() && $productTypeId !== 'grouped');
    $priceProperties = '';
    if ($useRichSnippets) {
        $priceProperties = $helperSnippets->getPriceProperties($_product); //Has to be called before getOfferItemscope
    }
 
//Get grid classes for product page sections
    $grid = $helperThis->getGridClasses();

//Product collaterals
//--------------------------------------------------------------
    $section = array();
    $relatedProductsHtml = '';
    $upsellProductsHtml = '';

//Related products.
//If related products not assigned to collateral data container.
    if (!$theme->getCfg('product_page/collateral_related')) {
        $replaceRelated = $theme->getCfg('product_page/replace_related');
        if ($replaceRelated == 1) { //don't replace with static block
            if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
                $relatedProductsHtml = $tmpHtml;
            //$relatedProductsHtml = trim($this->getChildHtml('related_products_wrapper'));
        }
        elseif ($replaceRelated == 2) { //if related is empty, replace with static block
            if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
                $relatedProductsHtml = $tmpHtml;
            else //related empty
            if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
                $relatedProductsHtml = '<div class="block_product_replace_related">' . $tmpHtml . '</div>';
        }
        elseif ($replaceRelated == 3) { //replace with static block
            if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
                $relatedProductsHtml = '<div class="block_product_replace_related">' . $tmpHtml . '</div>';
        }
    }

//Up-sell products.
//If up-sell products not assigned to collateral data container.
    if (!$theme->getCfg('product_page/collateral_upsell')) {
        $replaceUpsell = $theme->getCfg('product_page/replace_upsell');
        if ($replaceUpsell == 1) { //don't replace with static block
            if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
                $upsellProductsHtml = $tmpHtml;
            //$upsellProductsHtml = $this->getChildHtml('upsell_products_wrapper');
        }
        elseif ($replaceUpsell == 2) { //if upsell is empty, replace with static block
            if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
                $upsellProductsHtml = $tmpHtml;
            else //upsell empty
            if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
                $upsellProductsHtml = '<div class="block_product_replace_upsell">' . $tmpHtml . '</div>';
        }
        elseif ($replaceUpsell == 3) { //replace with static block
            if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
                $upsellProductsHtml = '<div class="block_product_replace_upsell">' . $tmpHtml . '</div>';
        }
    }

//Assign blocks to selected position
    $p = array();

//Related products
    $position = $theme->getCfg('product_page/related_position');
    if (isset($p[$position]))
        $p[$position] = $p[$position] . $relatedProductsHtml;
    else
        $p[$position] = $relatedProductsHtml;

//Up-sell products
    $position = $theme->getCfg('product_page/upsell_position');
    if (isset($p[$position]))
        $p[$position] = $p[$position] . $upsellProductsHtml;
    else
        $p[$position] = $upsellProductsHtml;

//Product collateral data (displayed as tabs or stacked blocks)
    $position = $theme->getCfg('product_page/collateral_position');
    if (isset($p[$position]))
        $p[$position] = $p[$position] . $this->getChildHtml('productCollaterals');
    else
        $p[$position] = $this->getChildHtml('productCollaterals');
    ?>

    <script type="text/javascript">
        var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    </script>
    <?php
    $color = $simpleProduct->getColor();
    $size = $_product->getSize();
//        $attr = Mage::getModel('eav/entity_attribute')->getCollection()->addFieldToFilter('frontend_label', 'Color');

    $productColor = Mage::getModel('catalog/product')->setStoreId(3)->setColor($color); // not loading the product - just creating a simple instance
    $productSize = Mage::getModel('catalog/product')->setStoreId(3)->setSize($size);

    $colorLabel = $productColor->getAttributeText('color');
    $sizeLabel = $productSize->getAttributeText('size');

    ?>
    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="product-view nested-container" <?php if ($useRichSnippets) echo $helperSnippets->getProductItemscope(); ?>>

        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

            <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-img-column <?php echo $grid['imgCol']; ?>">

                <?php echo $this->getChildHtml('media') ?>
                <?php echo $this->helper('ultimo/labels')->getLabels($_product); //Product labels  ?>
                <?php echo $this->getChildHtml('container_product_image_1'); ?>
                                       
            </div>

            <div class="product-primary-column product-shop <?php echo $grid['primCol']; ?>">

                <div class="product-name">
                    <p itemprop="name"><?php echo $_helper->productAttribute($simpleProduct, $simpleProduct->getName(), 'name')?></p>
                </div>

                <?php echo $this->getReviewsSummaryHtml($simpleProduct, false, true); //reviews ?>

                <?php if ($shortDescription): ?>
                    <div class="short-description"><div class="std" itemprop="description"><?php echo $shortDescription; ?></div></div>
                <?php endif; ?>

                <?php echo $this->getChildHtml('container_product_primary_1'); ?>

                <?php if (isset($p['primCol_1'])) echo $p['primCol_1']; ?>

                <?php if ($sku = $_product->getSku()): ?>
                    <?php if ($theme->getCfg('product_page/sku')): ?>
                        <div class="sku">
                            <span class="label"><?php echo $this->__('SKU'); ?>: </span>
                            <span class="value"><?php echo $sku; ?></span>
                        </div>
                    <?php endif; ?>
                    <?php if ($useRichSnippets): ?><meta itemprop="productID" content="sku:<?php echo $sku; ?>" /><?php endif; ?>
                <?php endif; ?>

                <?php echo $this->getChildHtml('alert_urls'); //alerts ?>

                <?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments  ?>
                    <div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
                <?php endif; ?>

                <div <?php if ($useRichSnippets) echo $helperSnippets->getOfferItemscope(); ?>>
                    <div class="product-type-data<?php echo $productTypeClasses; ?>"><?php echo $this->getChildHtml('product_type_data'); ?></div>
                    <?php echo $this->getTierPriceHtml(); ?>
                    <?php echo $priceProperties; ?>
                </div> <?php //end: offers          ?>
                <?php if (!$this->hasOptions()): //add to cart when no options (e.g. simple products) ?>
                    <?php if ($_product->isSaleable()): ?>
                        <div class="add-to-box">
                            <?php echo $this->getChildHtml('addtocart') ?>
                        </div>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php endif; ?>
                   
                <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                    <?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
                        <div class="container1-wrapper"><?php echo $container1_html; ?></div>
                    <?php endif; ?>
                <?php endif; ?>
  
                <?php if ($addtoLinksHtml = $this->getChildHtml('addto')): //compare, wishlist, send to friend ?>
                    <div class="action-box clearer">
                        <?php echo $addtoLinksHtml; ?>
                    </div>
                <?php endif; ?>

                <?php if (isset($p['primCol_2'])) echo $p['primCol_2']; ?>

                <?php echo $this->getChildHtml('other'); ?>

                <?php echo $this->getChildHtml('container_product_primary_2'); ?>

                <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                    <?php 
                    if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
                        <div class="box-additional <?php echo $grid['cont2Col']; ?>">
                            <div class="container2-wrapper"><?php echo $container2_html; ?></div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>

            </div> <!-- end: product-shop -->

            <?php if (isset($grid['secCol'])): //(!empty($secondaryColUnits)): ?>

                <div class="product-secondary-column <?php echo $grid['secCol']; ?> custom-sidebar-right">
                    <div class="inner">

                        <?php echo $this->getChildHtml('container_product_secondary_1'); ?>

                        <?php if (isset($p['secCol_1'])) echo $p['secCol_1']; ?>

                        <?php if ($tmpHtml = $this->getChildHtml('product_secondary_top_placeholder')): //Brand logo  ?>
                            <div class="feature-wrapper bottom-border"><?php echo $tmpHtml; ?></div>
                        <?php endif; ?>

                        <?php if (isset($p['secCol_2'])) echo $p['secCol_2']; ?>

                        <?php echo $this->getChildHtml('container_product_secondary_2'); ?>

                        <?php if (isset($p['secCol_3'])) echo $p['secCol_3']; ?>

                    </div>
                </div> <!-- end: product-secondary-column -->

            <?php endif; ?>
            <div class="clearer"></div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url) {
                if (this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>

        <?php //Lower primary column  ?>
        <div class="box-additional <?php echo $grid['lowerPrimCol']; ?>">

            <?php if (isset($p['lowerPrimCol_1'])) echo $p['lowerPrimCol_1']; ?>

            <?php echo $this->getChildHtml('product_additional_data') ?>

            <?php echo $this->getChildHtml('reviews'); //Reviews  ?>

        </div> <!-- end: box-tabs -->

        <?php //Lower secondary column  ?>
        <?php if (isset($p['lowerSecCol'])): ?>
            <div class="box-additional box-sidebar custom-sidebar-right <?php echo $p['lowerSecCol']; ?>">
                <div class="inner"><?php echo $p['lowerSecCol']; ?></div>
            </div>
        <?php endif; ?>

        <?php if (isset($p['lowerPrimCol_2'])): ?>
            <div class="box-additional <?php echo $p['lowerPrimCol_2']; ?>"><?php echo $p['lowerPrimCol_2']; ?></div>
        <?php endif; ?>

        <div class="clearer"></div>

        <div class="extras-panel">
            <div class="grid12-6 closer">
                <h3><?php echo $this->__('CLOSER LOOK') ?></h3>
                <?php
                $product = $this->getProduct();
                $images = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages(true, true)->toArray();
                if ($images['totalRecords'] != 0) {
                    ?>
                    <div class="jcarousel-wrapper">
                        <div class="jcarousel">
                            <ul>
                                <?php
                                foreach ($images['items'] as $image) {
                                    if (file_exists($image['path'])) {
                                        ?>
                                        <li>
                                            <a href="<?php echo $image['url']; ?>" class="showImage">
                                                <img src="<?php echo $image['url']; ?>" alt="" />
                                            </a>
                                        </li>
                                        <?php
                                    }
                                }
                                ?> 
                            </ul>
                        </div>

                        <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                        <a href="#" class="jcarousel-control-next">&rsaquo;</a>

                        <p class="jcarousel-pagination"></p>
                    </div>                      
                <?php } ?>
            </div>
            <div class="grid12-3">
                <h3><?php echo $this->__('RECOMENDED BY'); ?></h3>
                <?php
                $teamid = Mage::helper('attributeoptionimage')->getAttributeOptionImage($_product->getRecomended_by(), false);
                $teamModel = Mage::getModel('ourteam/ourteam')->load($teamid);

//            $teamModel = Mage::getModel('ourteam/ourteam')->getCollection();
                $teamdata = $teamModel->getData();
                $url = '';
                if(isset($teamdata['image'])):
                    $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'ourteam/image' . $teamdata['image'];
                endif;
                
//            $abc = Mage::helper('attributeoptionimage')->getAttributeOptionImage($_product->getRecomended_by());
                ?>
                <?php if (strpos($url, 'png') || strpos($url, 'jpg')) { ?>
                    <a href="<?php echo $teamModel->getOurteamUrl() ?>" title=""><img src="<?php echo $url ?>" alt="" /></a>
                <?php } ?>            
            </div>
            <div class="grid12-3 details">
                <h3><?php echo $this->__('MORE DETAILS'); ?></h3>
                <?php echo $this->getChildHtml('title_media_video'); ?>
                <?php $categoryId = $_product->getCategoryId(); ?>
                <?php
                $category = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($categoryId);
                $childCate = Mage::getModel('catalog/category')->getCategories($categoryId);

                //get All Product Category
                $allCate = Mage::getModel('catalog/product')->load($_product->getId())->getCategoryIds();
                $allCate = array_reverse($allCate);
                ?>
                <?php
                if (!empty($allCate) && $category->getChildren_count() > 0) {
                    foreach ($allCate as $cate) {
                        $_lastCategory = Mage::getModel('catalog/category')->load($cate);
                        $_description = $_lastCategory->getDescription();
                        if (!empty($_description)) {
                            $_description = $this->helper('catalog/output')->categoryAttribute($cate, $_description, 'description');
                        }
                        break;
                    }
                } else {
                    $_description = $category->getDescription();
                    if (!empty($_description)) {
                        $_description = $this->helper('catalog/output')->categoryAttribute($category, $_description, 'description');
                    }
                }
                if (strpos($_description, 'jpg') || strpos($_description, 'png')) {
                    ?>
                    <a href="javascript:void(0)" class="btn-fit-guide"><?php echo $this->__('FIT GUIDE'); ?></a>
                <?php } ?>
            </div>
            <div class="clearer"></div>
            <?php echo $this->getChildHtml('media_video'); ?>
            <div class="imageFitGuide" >
                <?php
                if (strpos($_description, 'jpg') || strpos($_description, 'png')) {
                    echo $_description;
                }
                ?>
            </div>
        </div>
    </div> <!-- end: product-view -->
    <style type="text/css">
        .product-name h1,.product-name > p  {
            color: #00af40;
            font-size: 24px;
            font-family: "Din Alternate Bold";
    font-weight: 400;
    line-height: 1.25em;
    margin: 0
        }
    </style>
    <?php }
?>